server:
  port: 8080
  servlet:
    session:
      timeout: 10m # 기본 30분, 최소는 1분

# logging 레벨 설정
logging:
  level:
    root: INFO
    sql: ERROR
#    org.springframework.web: debug
#    org.springframework.security: debug
